---
- name: Configure and Start Elasticsearch
  hosts: elastic_hosts
  become: true
  tasks:
    - name: Check if Elasticsearch is installed
      ansible.builtin.command: dpkg -s elasticsearch
      register: es_installed
      failed_when: es_installed.rc > 1
      changed_when: false
      ignore_errors: true

    - name: Fail if Elasticsearch is not installed
      ansible.builtin.fail:
        msg: "Elasticsearch is not installed! Please install it manually first."
      when: es_installed.rc != 0

    - name: Ensure Elasticsearch configuration is in place
      ansible.builtin.template:
        src: config/elasticsearch/elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: elasticsearch
        group: elasticsearch
        mode: "0644"
      notify: Restart Elasticsearch

    - name: Ensure Elasticsearch service is enabled and started
      ansible.builtin.service:
        name: elasticsearch
        enabled: true
        state: restarted
      ignore_errors: true

    - name: Verify Elasticsearch availability
      ansible.builtin.uri:
        url: "http://localhost:9200"
        user: "admin"
        password: "password123"
        force_basic_auth: yes
        method: GET
        status_code: 200
      register: elasticsearch_status
      ignore_errors: true

    - name: Show Elasticsearch status
      ansible.builtin.debug:
        var: elasticsearch_status

  handlers:
    - name: Restart Elasticsearch
      ansible.builtin.service:
        name: elasticsearch
        state: restarted

- name: Install Filebeat
  hosts: webservers
  become: true
  tasks:
    - name: Add Yandex Elastic repository
      ansible.builtin.shell: |
        echo "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main" | sudo tee /etc/apt/sources.list.d/elastic-8.x.list

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Filebeat
      ansible.builtin.apt:
        name: filebeat
        state: present
        update_cache: yes
      ignore_errors: true


- name: Configure and Start Kibana
  hosts: kibana_hosts
  become: true
  tasks:
    - name: Install Kibana
      ansible.builtin.apt:
        name: kibana
        state: present

    - name: Deploy Kibana configuration
      template:
        src: config/kibana/kibana.yml.j2
        dest: /etc/kibana/kibana.yml
        owner: kibana
        group: kibana
        mode: "0644"
      notify: Restart Kibana

    - name: Ensure Kibana service is enabled and started
      ansible.builtin.service:
        name: kibana
        enabled: true
        state: started

  handlers:
    - name: Restart Kibana
      ansible.builtin.service:
        name: kibana
        state: restarted

